
reservedWords = Dict{String, Any}()
reservedWords["SentenceType"] = Set{AbstractString}()
push!(reservedWords["SentenceType"], "is")
push!(reservedWords["SentenceType"], "react")
push!(reservedWords["SentenceType"], "uptake")
push!(reservedWords["SentenceType"], "secrete")
push!(reservedWords["SentenceType"], "bind")
push!(reservedWords["SentenceType"], "unbind")
push!(reservedWords["SentenceType"], "phosphorylate")
push!(reservedWords["SentenceType"], "dephosphorylate")
push!(reservedWords["SentenceType"], "induce")
push!(reservedWords["SentenceType"], "activate")
push!(reservedWords["SentenceType"], "repress")
push!(reservedWords["SentenceType"], "inhibit")
push!(reservedWords["SentenceType"], "catalyze")
reservedWords["the"] = "negligible"
reservedWords["The"] = "negligible"
reservedWords["cell"] = "negligible"
reservedWords["together"] = "negligible"
reservedWords["to"] = "negligible"
reservedWords["form"] = "negligible"
reservedWords["expression"] = "negligible"
reservedWords["of"] = "negligible"
reservedWords["transcription"] = "negligible"
reservedWords["translation"] = "negligible"
reservedWords["conversion"] = "negligible"
reservedWords["is"] = "is"
reservedWords["was"] = "is"
reservedWords["are"] = "is"
reservedWords["were"] = "is"
reservedWords["react"] = "react"
reservedWords["reacted"] = "react"
reservedWords["reacting"] = "react"
reservedWords["reacts"] = "react"
reservedWords["into"] = "into"
reservedWords["irreversible"] = "irreversible"
reservedWords["irreversibly"] = "irreversible"
reservedWords["uptake"] = "uptake"
reservedWords["uptakes"] = "uptake"
reservedWords["uptaking"] = "uptake"
reservedWords["uptook"] = "uptake"
reservedWords["via"] = "via"
reservedWords["through"] = "via"
reservedWords["the"] = "negligible"
reservedWords["cell"] = "negligible"
reservedWords["secrete"] = "secrete"
reservedWords["secretes"] = "secrete"
reservedWords["secreting"] = "secrete"
reservedWords["secreted"] = "secrete"
reservedWords["via"] = "via"
reservedWords["through"] = "via"
reservedWords["the"] = "negligible"
reservedWords["cell"] = "negligible"
reservedWords["bind"] = "bind"
reservedWords["bound"] = "bind"
reservedWords["binds"] = "bind"
reservedWords["binding"] = "bind"
reservedWords["associate"] = "bind"
reservedWords["associates"] = "bind"
reservedWords["associated"] = "bind"
reservedWords["associating"] = "bind"
reservedWords["complex"] = "bind"
reservedWords["complexes"] = "bind"
reservedWords["complexed"] = "bind"
reservedWords["complexing"] = "bind"
reservedWords["into"] = "into"
reservedWords["together"] = "negligible"
reservedWords["unbind"] = "unbind"
reservedWords["unbinds"] = "unbind"
reservedWords["unbound"] = "unbind"
reservedWords["unbinding"] = "unbind"
reservedWords["dissociate"] = "unbind"
reservedWords["dissociates"] = "unbind"
reservedWords["dissociated"] = "unbind"
reservedWords["dissociating"] = "unbind"
reservedWords["into"] = "into"
reservedWords["phosphorylate"] = "phosphorylate"
reservedWords["phosphorylates"] = "phosphorylate"
reservedWords["phosphorylated"] = "phosphorylate"
reservedWords["phosphorylating"] = "phosphorylate"
reservedWords["reversibly"] = "reversible"
reservedWords["reversible"] = "reversible"
reservedWords["at"] = "at"
reservedWords["site"] = "site"
reservedWords["dephosphorylate"] = "dephosphorylate"
reservedWords["dephosphorylates"] = "dephosphorylate"
reservedWords["dephosphorylated"] = "dephosphorylate"
reservedWords["dephosphorylating"] = "dephosphorylate"
reservedWords["at"] = "at"
reservedWords["site"] = "site"
reservedWords["activate"] = "activate"
reservedWords["activates"] = "activate"
reservedWords["activating"] = "activate"
reservedWords["activated"] = "activate"
reservedWords["promote"] = "induce"
reservedWords["promotes"] = "induce"
reservedWords["promoting"] = "induce"
reservedWords["promoted"] = "induce"
reservedWords["induce"] = "induce"
reservedWords["induces"] = "induce"
reservedWords["inducing"] = "induce"
reservedWords["induced"] = "induce"
reservedWords["upregulate"] = "activate"
reservedWords["upregulates"] = "activate"
reservedWords["upregulated"] = "activate"
reservedWords["upregulating"] = "activate"
reservedWords["the"] = "negligible"
reservedWords["expression"] = "negligible"
reservedWords["of"] = "negligible"
reservedWords["transcription"] = "negligible"
reservedWords["translation"] = "negligible"
reservedWords["inhibit"] = "inhibit"
reservedWords["inhibits"] = "inhibit"
reservedWords["inhibiting"] = "inhibit"
reservedWords["inhibited"] = "inhibit"
reservedWords["repress"] = "repress"
reservedWords["represses"] = "repress"
reservedWords["repressing"] = "repress"
reservedWords["repressed"] = "repress"
reservedWords["downregulate"] = "repress"
reservedWords["downregulates"] = "repress"
reservedWords["downregulated"] = "repress"
reservedWords["downregulating"] = "repress"
reservedWords["the"] = "negligible"
reservedWords["expression"] = "negligible"
reservedWords["of"] = "negligible"
reservedWords["transcription"] = "negligible"
reservedWords["translation"] = "negligible"
reservedWords["catalyze"] = "catalyze"
reservedWords["catalyzes"] = "catalyze"
reservedWords["catalyzed"] = "catalyze"
reservedWords["catalyzing"] = "catalyze"
reservedWords["catalyse"] = "catalyze"
reservedWords["catalyses"] = "catalyze"
reservedWords["catalysed"] = "catalyze"
reservedWords["catalysing"] = "catalyze"
reservedWords["reversible"] = "reversible"
reservedWords["into"] = "into"
reservedWords["the"] = "negligible"
reservedWords["conversion"] = "negligible"
reservedWords["of"] = "negligible"